### ISSUE TITLE
Please help me!, I got this problem.

### ISSUE THREAD

**Issue by babymilo** [georgesung/ssd_tensorflow_traffic_sign_detection#14]
Traceback (most recent call last):
  File "inference.py", line 189, in <module>
    generate_output(input_files, mode)
  File "inference.py", line 125, in generate_output
    model = SSDModel()
  File "/Users/PEE/tensorflow/models/object_detection/ssd_tensorflow_traffic_sign_detection/model.py", line 178, in SSDModel
    model = AlexNet()
  File "/Users/PEE/tensorflow/models/object_detection/ssd_tensorflow_traffic_sign_detection/model.py", line 159, in AlexNet
    final_pred_conf = tf.concat(1, preds_conf)
  File "/Users/PEE/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1043, in concat
    dtype=dtypes.int32).get_shape(
  File "/Users/PEE/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 676, in convert_to_tensor
    as_ref=False)
  File "/Users/PEE/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/PEE/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/PEE/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/PEE/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 374, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Users/PEE/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by alonebaby** [comment]
the tensorflow version that you using is 1.0+? if it is, need upgrade some apis from tf_update.py.

**Comment by xiaoerlaigeid** [comment]
the code is old version, some api has changed.

**Comment by babymilo** [comment]
What should i do?

**Comment by georgesung** [comment]
Did you try using TensorFlow v0.12.0? The code was written for that version of TensorFlow. If you would like to use the latest version of TensorFlow, then you must modify the code according to the new TensorFlow API.
