### ISSUE TITLE
Error when run inference.py 

### ISSUE THREAD

**Issue by Caiyujie007** [georgesung/ssd_tensorflow_traffic_sign_detection#40]
I got this issue when run inference.py，can anyone help me? My python is python 2.7.5 and tensorflow is 1.1.0.

yjcai@inspur ssd_tensorflow_traffic_sign_detection]$ python inference.py -m demo
Traceback (most recent call last):
  File "inference.py", line 6, in <module>
    from model import SSDModel
  File "/export/userhome/yjcai/Documents/SSD/ssd_tensorflow_traffic_sign_detection/model.py", line 241
    box = (*box_coords, cls, cls_prob)
           ^
SyntaxError: invalid syntax

**Comment by amirtaherkhani** [comment]
using python =>3 and and switch to directory and using "python3 inference.py -m demo"
