### ISSUE TITLE
please help me, i am stuck in running inference.py

### ISSUE THREAD

**Issue by warmheartHoward** [georgesung/ssd_tensorflow_traffic_sign_detection#48]
Traceback (most recent call last):
  File "inference.py", line 189, in <module>
    generate_output(input_files, mode)
  File "inference.py", line 130, in generate_output
    saver.restore(sess, MODEL_SAVE_PATH)
  File "E:\anaconda\envs\opencv\lib\site-packages\tensorflow\python\training\saver.py", line 1268, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: ./model.ckpt

how to modify this code? thanks

**Comment by AuMgLi** [comment]
change File "./settings.py" line 51 to "MODEL_SAVE_PATH = './model/model.ckpt'"
