### ISSUE TITLE
Exception running inference.py

### ISSUE THREAD

**Issue by Kkevsterrr** [georgesung/ssd_tensorflow_traffic_sign_detection#51]
```

Traceback (most recent call last):
  File "inference.py", line 189, in <module>
    generate_output(input_files, mode)
  File "inference.py", line 125, in generate_output
    model = SSDModel()
  File "/Volumes/KCB_Storage/Users/koolkevin/Code/Courses/CMSC838J/final_project/ssd_tensorflow_traffic_sign_detection/model.py", line 178, in SSDModel
    model = AlexNet()
  File "/Volumes/KCB_Storage/Users/koolkevin/Code/Courses/CMSC838J/final_project/ssd_tensorflow_traffic_sign_detection/model.py", line 159, in AlexNet
    final_pred_conf = tf.concat(1, preds_conf)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1253, in concat
    dtype=dtypes.int32).get_shape().assert_is_compatible_with(
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1039, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1097, in convert_to_tensor_v2
    as_ref=False)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1102, in _autopacking_conversion_function
    return _autopacking_helper(v, dtype, name or "packed")
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1054, in _autopacking_helper
    return gen_array_ops.pack(elems_as_tensors, name=scope)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5448, in pack
    "Pack", values=values, axis=axis, name=name)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 1152 and 288. Shapes are [?,1152] and [?,288].
	From merging shape 2 with other shapes. for 'concat/concat_dim' (op: 'Pack') with input shapes: [?,17856], [?,4140], [?,1152], [?,288].
```
I get this with both -m demo and with -i for specific images.

**Comment by ManivannanMurugavel** [comment]
from model.py
change the line 159 and 160 to similar below
```
final_pred_conf = tf.concat(preds_conf, 1)
final_pred_loc = tf.concat(preds_loc, 1)
```
and change the line 57 into 
```
conf_loss = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits, labels=y_true_conf)
```
Finally change the line 68
```
loc_loss = tf.where(smooth_l1_condition, loc_loss_l2, loc_loss_l1)
```

It's worked fine.

**Comment by Kkevsterrr** [comment]
Works great - thanks!
